
import { ColorTheme } from './types';

export const COLOR_THEMES: ColorTheme[] = [
  {
    name: '🔵 블루-그레이',
    description: '차분하고 전문적인 느낌',
    colors: {
      primary: '#1a73e8',
      primaryDark: '#004d99',
      secondary: '#5f6368',
      background: '#f8f9fa',
      text: '#3c4043',
      highlightBg: '#e8f0fe',
      infoBoxBg: '#e8f4fd',
      infoBoxBorder: '#1a73e8',
      warningBoxBg: '#fce8e6',
      warningBoxBorder: '#d93025',
      tableHeaderBg: '#e8eaed',
      tableBorder: '#dadce0',
      tableEvenRowBg: '#f1f3f4',
    },
  },
  {
    name: '🌿 그린-오렌지',
    description: '활기차고 친근한 느낌',
    colors: {
      primary: '#34a853',
      primaryDark: '#1e8e3e',
      secondary: '#ea8600',
      background: '#f1f8e9',
      text: '#333333',
      highlightBg: '#fef6e0',
      infoBoxBg: '#e6f4ea',
      infoBoxBorder: '#34a853',
      warningBoxBg: '#fde293',
      warningBoxBorder: '#f9ab00',
      tableHeaderBg: '#e6f4ea',
      tableBorder: '#a5d6a7',
      tableEvenRowBg: '#f1f8e9',
    },
  },
  {
    name: '💜 퍼플-옐로우',
    description: '세련되고 창의적인 느낌',
    colors: {
      primary: '#8e44ad',
      primaryDark: '#6200ea',
      secondary: '#f1c40f',
      background: '#fdf6e3',
      text: '#2c3e50',
      highlightBg: '#fcf8e3',
      infoBoxBg: '#f3e5f5',
      infoBoxBorder: '#8e44ad',
      warningBoxBg: '#fff9c4',
      warningBoxBorder: '#f1c40f',
      tableHeaderBg: '#f3e5f5',
      tableBorder: '#ce93d8',
      tableEvenRowBg: '#faf3fb',
    },
  },
  {
    name: '🍵 틸-라이트그레이',
    description: '안정적이고 현대적인 느낌',
    colors: {
      primary: '#00796b',
      primaryDark: '#004d40',
      secondary: '#607d8b',
      background: '#eceff1',
      text: '#263238',
      highlightBg: '#e0f2f1',
      infoBoxBg: '#e0f7fa',
      infoBoxBorder: '#00796b',
      warningBoxBg: '#ffebee',
      warningBoxBorder: '#c62828',
      tableHeaderBg: '#cfd8dc',
      tableBorder: '#b0bec5',
      tableEvenRowBg: '#eceff1',
    },
  },
  {
    name: '🧱 테라코타-라이트그레이',
    description: '따뜻하고 편안한 느낌',
    colors: {
      primary: '#e57373',
      primaryDark: '#c62828',
      secondary: '#757575',
      background: '#fafafa',
      text: '#424242',
      highlightBg: '#ffcdd2',
      infoBoxBg: '#fbe9e7',
      infoBoxBorder: '#ff8a65',
      warningBoxBg: '#fff3e0',
      warningBoxBorder: '#ffa726',
      tableHeaderBg: '#eeeeee',
      tableBorder: '#e0e0e0',
      tableEvenRowBg: '#f5f5f5',
    },
  },
   {
    name: '👔 클래식 블루',
    description: '신뢰할 수 있고 안정적인 느낌',
    colors: {
      primary: '#0f4c81',
      primaryDark: '#002f6c',
      secondary: '#77aaff',
      background: '#f0f4f8',
      text: '#333333',
      highlightBg: '#e3f2fd',
      infoBoxBg: '#e3f2fd',
      infoBoxBorder: '#0f4c81',
      warningBoxBg: '#ffebee',
      warningBoxBorder: '#d32f2f',
      tableHeaderBg: '#d6e4f0',
      tableBorder: '#b0bec5',
      tableEvenRowBg: '#f0f4f8',
    },
  },
  {
    name: '🌳 네이처 그린',
    description: '생기 있고 조화로운 느낌',
    colors: {
      primary: '#2e7d32',
      primaryDark: '#005005',
      secondary: '#aed581',
      background: '#f1f8e9',
      text: '#212121',
      highlightBg: '#dcedc8',
      infoBoxBg: '#e8f5e9',
      infoBoxBorder: '#2e7d32',
      warningBoxBg: '#fffde7',
      warningBoxBorder: '#fbc02d',
      tableHeaderBg: '#c8e6c9',
      tableBorder: '#a5d6a7',
      tableEvenRowBg: '#f1f8e9',
    },
  },
];